---
repos:
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.13.1
    hooks:
      - id: stylua-github
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        args: ["-d {extends: relaxed, rules: {line-length: disable}}", "-s"]
