---
repos:
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.15.1
    hooks:
      - id: stylua-github
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.28.0
    hooks:
      - id: yamllint
        args: ["-d {extends: relaxed, rules: {line-length: disable}}", "-s"]
