---

- hosts: localhost
  become: yes
  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"

  tasks:
    - name: Initial setup 
      include_tasks: tasks/initial_setup.yml

    - name: git config 
      include_tasks: tasks/git.yml
