---

- hosts: localhost
  vars:
    discord_version: 0.0.17
    geekbench_version: 5.4.4
    go_version: 1.18.3
    home_dir: "{{ lookup('env', 'HOME') }}"
    wallpaper_url: https://preview.redd.it/nlseh8bcvfq81.jpg?width=3840&format=pjpg&auto=webp&s=dda5aba0c1e750d717c7fa90a2355aeafc027861

    # These are git tags
    nvim_version: v0.7.0
    lua_lsp_version: 3.2.5
    i3lock_version: 2.13.c.4

  tasks:
    - name: Initial setup
      include_tasks: tasks/initial_setup.yml

    - name: Configure Git
      include_tasks: tasks/git.yml

    - name: Misc terminal tools
      include_tasks: tasks/misc.yml

    - name: Configure python3
      include_tasks: tasks/python.yml

    - name: Configure GoLang
      include_tasks: tasks/go.yml

    - name: Set up zsh shell
      include_tasks: tasks/zsh.yml

    - name: Set up i3 window manager
      include_tasks: tasks/i3.yml

    - name: Set up Neovim
      include_tasks: tasks/nvim.yml

    - name: Install desktop apps
      include_tasks: tasks/apps.yml

    - name: Final Cleanup
      include_tasks: tasks/final.yml
