---

- hosts: localhost
  become: true
  tasks:

    - name: Initial setup 
    include_tasks: initial_setup.yml 

    - name: Configure git 
    include_tasks: git.yml

    - name: Install misc tools
    include_tasks: misc.yml

    - name: Configure i3wm
    include_tasks: i3.yml

    - name: Neovim
    include_tasks: nvim.yml
