---

- hosts: localhost
  become: true
  tasks:

    - name: Ansible requirements
      shell: ansible-galaxy collection install community.general

    - name: Initial setup 
    include_tasks: initial_setup.yml 

    - name: Configure git 
    include_tasks: git.yml

    - name: Install misc tools
    include_tasks: misc.yml

    - name: Configure zsh shell
    include_tasks: zsh.yml

    - name: Configure i3wm
    include_tasks: i3.yml

    - name: Install Python3 env
    include_tasks: python.yml

    - name: Neovim
    include_tasks: nvim.yml

    - name: Final Steps
    include_tasks: final.yml
