---

- hosts: localhost
  vars:
    go_version: 1.21.0
    home_dir: "{{ lookup('env', 'HOME') }}"

    # These are git tags
    nvim_version: v0.9.1
    lua_lsp_version: 3.6.25
    i3lock_version: 2.13.c.4

  tasks:
    - name: Initial setup
      include_tasks: tasks/initial_setup.yml

    - name: Configure Git
      include_tasks: tasks/git.yml

    - name: Misc terminal tools
      include_tasks: tasks/misc.yml

    - name: Configure python3
      include_tasks: tasks/python.yml

    - name: Configure GoLang
      include_tasks: tasks/go.yml

    - name: Configure Rust
      include_tasks: tasks/rust.yml

    - name: Configure Javascript
      include_tasks: tasks/javascript.yml

    - name: Set up zsh shell
      include_tasks: tasks/zsh.yml

    - name: Set up Neovim
      include_tasks: tasks/nvim.yml

    - name: Install desktop apps
      include_tasks: tasks/apps.yml

    - name: Final Cleanup
      include_tasks: tasks/final.yml
