---

# TODO: Replace file copies with symlinks
- hosts: localhost
  vars:
    discord_version: 0.0.19
    geekbench_version: 5.4.5
    go_version: 1.19.0
    home_dir: "{{ lookup('env', 'HOME') }}"

    # These are git tags
    nvim_version: v0.7.2
    lua_lsp_version: 3.5.3
    i3lock_version: 2.13.c.4

  tasks:
    - name: Initial setup
      include_tasks: tasks/initial_setup.yml

    - name: Configure Git
      include_tasks: tasks/git.yml

    - name: Misc terminal tools
      include_tasks: tasks/misc.yml

    - name: Configure python3
      include_tasks: tasks/python.yml

    - name: Configure GoLang
      include_tasks: tasks/go.yml

    - name: Set up zsh shell
      include_tasks: tasks/zsh.yml

    - name: Set up i3 window manager
      include_tasks: tasks/i3.yml

    - name: Set up Neovim
      include_tasks: tasks/nvim.yml

    - name: Install desktop apps
      include_tasks: tasks/apps.yml

    - name: Final Cleanup
      include_tasks: tasks/final.yml
