---

- hosts: localhost
  vars:
    discord_version: 0.0.17
    geekbench_version: 5.4.4
    home_dir: "{{ lookup('env', 'HOME') }}"

    # These are git tags
    nvim_version: v0.6.1
    alacritty_version: v0.10.1

  tasks:
    - name: Initial setup 
      include_tasks: tasks/initial_setup.yml

    - name: Configure Git 
      include_tasks: tasks/git.yml

    - name: Misc terminal tools 
      include_tasks: tasks/misc.yml

        #TODO: Add ghstats and remove py310 install/deadsnakes
        #- name: Configure python3
        #include_tasks: tasks/python.yml

    - name: Set up zsh shell 
      include_tasks: tasks/zsh.yml

    - name: Set up Neovim 
      include_tasks: tasks/nvim.yml

    - name: Install desktop apps
      include_tasks: tasks/apps.yml

    - name: Final Cleanup
      include_tasks: tasks/final.yml
