---

- hosts: localhost
  become: yes
  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
    discord_version: 0.0.17

  tasks:
    - name: Initial setup 
      include_tasks: tasks/initial_setup.yml 

    - name: Configure git 
      include_tasks: tasks/git.yml

    - name: Install misc tools
      include_tasks: tasks/misc.yml

    - name: Configure zsh shell
      include_tasks: tasks/zsh.yml

    - name: Configure i3wm
      include_tasks: tasks/i3.yml

    - name: Install Python3 env
      include_tasks: tasks/python.yml

    - name: Configure Neovim
      include_tasks: tasks/nvim.yml

    - name: Install Desktop Applications
      include_tasks: tasks/apps.yml

    - name: Final Steps
      include_tasks: tasks/final.yml
