---

- hosts: localhost
  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
    nvim_version: v0.6.1

  tasks:
    - name: Initial setup 
      include_tasks: tasks/initial_setup.yml

    - name: git config 
      include_tasks: tasks/git.yml

    - name: Misc terminal tools 
      include_tasks: tasks/misc.yml

    - name: Set up zsh shell 
      include_tasks: tasks/zsh.yml

    - name: Set up Neovim 
      include_tasks: tasks/nvim.yml
