---

- name: Install Alacritty
  apt:
    name: alacritty
  become: true

- name: Move config file
  file:
    src: "{{ home_dir }}/Workspace/dotfiles-playbook/templates/alacritty-config/alacritty.yml"
    dest: "{{ home_dir }}/.config/alacritty/alacritty.yml"
    state: link

- name: Add appimagelauncher PPA
  apt_repository:
    repo: ppa:appimagelauncher-team/stable
  become: true

- name: Install appimagelauncher
  apt:
    name: appimagelauncher
  become: true

- name: Install Cheese
  apt:
    name: cheese
  become: true

# /usr/share/discord/
- name: Install Discord flatpak
  block:
    - name: Install flatpak
      apt:
        name: 
          - flatpak
          - gnome-software
          - gnome-software-plugin-flatpak
      become: True

    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      become: True

    - name: Install discord
      community.general.flatpak:
        name: com.discordapp.Discord
        state: present

- name: Install firefox
  include_tasks: build_firefox.yml

- name: Install flameshot
  apt:
    name: flameshot
  become: true

- name: Install gnome-boxes
  apt:
    name: gnome-boxes
  become: true

- name: Install Libreoffice
  apt:
    name: libreoffice
  become: true

- name: Install Notion
  get_url:
    url: "https://github.com/notion-enhancer/notion-repackaged/releases/download/v2.0.18-1/Notion-2.0.18-1.AppImage"
    dest: "{{ home_dir }}/Applications/"
    mode: 0755
  become: true

- name: Install rpi-imager
  apt:
    name: rpi-imager
  become: true
#
- name: Install VLC
  apt:
    name: vlc
  become: true

# Tests
# firefox tests
# Launch alacritty from terminal
# Launch geekbench and check version
# Launch discord
# Launch notion
