---

- name: Install Alacritty
  community.general.snap:
    name: alacritty
    classic: yes

# Move alacritty.yml

- name: Install Bitwarden
  community.general.snap:
    name: bitwarden
    classic: yes

- name: Install Blender
  community.general.snap:
    name: blender
    classic: yes

- name: Install Cheese
  apt:
    name: cheese

- name: Install Discord
  community.general.snap:
    name: discord
    classic: yes

- name: Install Libreoffice
  community.general.snap:
    name: libreoffice
    classic: yes

- name: Install Notion
  community.general.snap:
    name: notion-snap
    classic: yes

- name: Install VLC
  community.general.snap:
    name: vlc 
    classic: yes

# Not available on Snap
- name: Download geekbench
  get_url:
    url: https://cdn.geekbench.com/Geekbench-5.4.4-Linux.tar.gz
    dest: "/tmp/geekbench"
    mode: 0755

- name: Install geekbench
  unarchive:
    src: "/tmp/geekbench"
    dest: "{{ home_dir }}/Downloads/geekbench"

# Not on Snap
#- name: Install ublock


