---

- name: Download Alacritty from apt
  apt:
    name: alacritty
  become: true
  when: not (ansible_facts['distribution'] == 'Ubuntu') and not (ansible_facts['distribution_release'] == 'jammy')

- name: Download Alacritty .deb
  apt:
    deb: https://github.com/barnumbirr/alacritty-debian/releases/download/v0.10.1-1/alacritty_0.10.1-1_amd64_bullseye.deb
  become: true
  when: (ansible_facts['distribution'] == 'Ubuntu') and (ansible_facts['distribution_release'] == 'jammy')

- name: Move config file
  copy:
    src: templates/alacritty-config/alacritty.yml
    dest: "{{ home_dir }}/.config/alacritty/alacritty.yml"

- name: Add appimagelauncher PPA
  apt_repository:
    repo: ppa:appimagelauncher-team/stable
  become: true

- name: Install appimagelauncher
  apt:
    name: appimagelauncher
  become: true

- name: Install Cheese
  apt:
    name: cheese
  become: true

# /usr/share/discord/
- name: Install Discord
  apt:
    deb: 'https://dl.discordapp.net/apps/linux/{{ discord_version }}/discord-{{ discord_version }}.deb'
  become: true

- name: Install firefox
  include_tasks: build_firefox.yml

- name: Install flameshot
  apt:
    name: flameshot
  become: true

- name: Download Geekbench
  get_url:
    url: "https://cdn.geekbench.com/Geekbench-{{geekbench_version}}-Linux.tar.gz"
    dest: "{{ home_dir }}/Downloads/Geekbench-{{geekbench_version}}-Linux.tar.gz"
    mode: 0755

- name: Install Geekbench
  unarchive:
    src: "{{ home_dir }}/Downloads/Geekbench-{{geekbench_version}}-Linux.tar.gz"
    dest: "{{ home_dir }}/Applications/"
    mode: 0755
  become: true

- name: Install gnome-boxes
  apt:
    name: gnome-boxes
  become: true

- name: Install Libreoffice
  apt:
    name: libreoffice
  become: true

- name: Install Notion
  get_url:
    url: "https://github.com/notion-enhancer/notion-repackaged/releases/download/v2.0.18-1/Notion-2.0.18-1.AppImage"
    dest: "{{ home_dir }}/Applications/"
    mode: 0755
  become: true

- name: Install rpi-imager
  apt:
    name: rpi-imager
  become: true
#
- name: Install VLC
  apt:
    name: vlc
  become: true

# Tests
# firefox tests
# Launch alacritty from terminal
# Launch geekbench and check version
# Launch discord
# Launch notion
