---

- name: Install alacritty
  include_tasks: build_alacritty.yml

- name: Distribute alacritty config
  copy:
    src: templates/alacritty-config/alacritty.yml
    dest: "{{ home_dir }}/.alacritty.yml"

- name: Install Cheese
  apt:
    name: cheese
  become: yes

#/usr/share/discord/
- name: Install discord
  apt:
    deb: 'https://dl.discordapp.net/apps/linux/{{ discord_version }}/discord-{{ discord_version }}.deb'
  become: yes

#TODO: Build firefox after verifying py3

- name: Download geekbench
  get_url:
    url: "https://cdn.geekbench.com/Geekbench-{{geekbench_version}}-Linux.tar.gz"
    dest: "{{ home_dir }}/Downloads/Geekbench-{{geekbench_version}}-Linux.tar.gz"
    mode: 0755

- name: Install geekbench
  unarchive:
    src: "{{ home_dir }}/Downloads/Geekbench-{{geekbench_version}}-Linux.tar.gz"
    dest: "/usr/bin/"
    include:
      - geekbench5
  become: yes

- name: Install gnome-boxes
  apt:
    name: gnome-boxes
  become: yes

- name: Install libreoffice
  apt:
    name: libreoffice
  become: yes

- name: Install notion
  get_url:
    url: "https://github.com/notion-enhancer/notion-repackaged/releases/download/v2.0.18-1/Notion-2.0.18-1.AppImage"
    dest: "/usr/bin/notion-repackaged.v2.0.10-1.AppImage"
    mode: 0755
  become: yes

- name: Install vlc
  include_tasks: build_vlc.yml


# Tests
# Launch alacritty from terminal
# Launch geekbench and check version
# Launch discord
# Launch notion
# Launch vlc
