---

- name: Install alacritty
  include_tasks: build_alacritty.yml

- name: Distribute alacritty config
  copy:
    src: templates/alacritty-config/alacritty.yml
    dest: "{{ home_dir }}/.alacritty.yml"

- name: Install Cheese
  apt:
    name: cheese
  become: yes

- name: Install discord
  apt:
    deb: 'https://dl.discordapp.net/apps/linux/{{ discord_version }}/discord-{{ discord_version }}.deb'
  become: yes

#TODO: Build firefox after verifying py3

- name: Download geekbench
  get_url:
    url: "https://cdn.geekbench.com/Geekbench-{{geekbench_version}}-Linux.tar.gz"
    dest: "{{ home_dir }}/Downloads/Geekbench-{{geekbench_version}}-Linux.tar.gz"

    mode: 0755

- name: Install geekbench
  unarchive:
    src: "{{ home_dir }}/Downloads/Geekbench-{{geekbench_version}}-Linux.tar.gz"
    dest: "{{ home_dir }}/Downloads/"

- name: Install gnome-boxes
  apt:
    name: gnome-boxes
  become: yes

- name: Install libreoffice
  apt:
    name: libreoffice
  become: yes

- name: Install notion
  apt:
    deb: "https://github.com/notion-enhancer/notion-repackaged/releases/download/v2.0.18-1/notion-app_2.0.18-1_arm64.deb"
  become: yes

- name: Install vlc
  include_tasks: build_vlc.yml


# Tests
