---

- name: Download wallpaper directory
  git:
    clone: true
    repo: https://gitlab.com/dwt1/wallpapers.git
    dest: "{{ home_dir }}/.wallpapers"

- name: Install Dependancies (pt1)
  apt:
    name: awesome
    state: build-dep
  become: true

- name: Install Dependancies (pt2)
  apt:
    name: libxcb-xfixes0-dev
  become: true

# Install master branch, or just install from apt for v4.3
- name: Clone repo
  git:
    clone: true
    dest: "{{ home_dir }}/Downloads/awesome"
    force: true
    repo: https://github.com/awesomeWM/awesome.git
    update: true

- name: Build awesome package
  make:
    chdir: "{{ home_dir }}/Downloads/awesome"
    target: package

- name: Install awesome
  apt:
    deb: "{{ lookup( 'fileglob', '{{ home_dir }}/Downloads/awesome/build/*.deb')}}"
  become: true

- name: Install Rofi searchbar
  apt:
    name: rofi
  become: true

- name: Install picom
  apt:
    name: picom
  become: true

- name: Distribute awesome config
  copy:
    src: templates/awesome-config/
    dest: "{{ home_dir }}/.config/awesome/"
