---
# TODO: Build from source
# https://ubuntuhandbook.org/index.php/2022/04/install-firefox-deb-ubuntu-22-04/

- name: Install firefox
  apt:
    name: firefox
  become: true

- name: Create distribution folder
  file:
    path: '/etc/firefox/policies'
    state: directory
    mode: 0755
  become: true

- name: Distribute firefox policy
  copy:
    src: templates/firefox/policies.json
    dest: "/etc/firefox/policies/policies.json"
  become: true

# TESTS
# Launch firefox
# Verify policies are applied
