---
#TODO: Build from source
- name: Remove snap Firefox
  community.general.snap:
    name: firefox
    state: absent
  become: yes

- name: Install firefox
  apt: 
    name: firefox
  become: yes

- name: Distribute firefox policy
  copy:
    src: templates/firefox/policies.json
    dest: "/usr/lib/firefox/distribution/policies.json"
  become: true

# TESTS
# Check /snap/firefox doesn't exist
# Launch firefox
# Verify policies are applied
