---

- name: Install dependancies
  apt:
    name:
      - git 
      - g++ 
      - make 
      - libtool 
      - automake 
      - autopoint 
      - pkg-config 
      - flex 
      - bison 
      - lua5.2
  become: yes

- name: Clone repo
  git:
    clone: yes
    dest: "{{ home_dir }}/Downloads/vlc"
    force: yes
    repo: git://git.videolan.org/vlc.git
    update: yes

- name: Bootstrap
  command: sh "{{ home_dir }}/Downloads/vlc/bootstrap"
