---

- name: Remove snap Firefox
  community.general.snap:
    name: firefox
    state: absent
  become: yes

- name: Add Flatpak
  apt:
    name: flatpak
  become: yes

- name: Add Flatpak repository
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present
  become: yes

- name: Install Flatpak Firefox
  community.general.flatpak:
    name: org.mozilla.firefox
  become: yes

#TODO: move config distribution here
