---

- name: Install dependancies
  apt:
    name:
      - build-essential 
      - git 
      - subversion 
      - cmake 
      - libx11-dev 
      - libxxf86vm-dev 
      - libxcursor-dev 
      - libxi-dev 
      - libxrandr-dev 
      - libxinerama-dev 
      - libglew-dev
  become: yes

# Source: https://github.com/chrisbrake/ansible/blob/master/blender.yml
- name: Get blender source
  git:
    repo: 'git://git.blender.org/blender.git'
    dest: '{{ home_dir }}/Downloads/blender'

- name: Run the build
  make:
    target: '{{ item }}'
    chdir: '{{ home_dir }}/Downloads/blender'
  with_items:
    - update
    - lite

- name: Install blender
  make:
    target: install
    chdir: '{{ home_dir }}/Downloads/blender'
    params:
      CMAKE_INSTALL_PREFIX: /opt/blender
      WITH_INSTALL_PORTABLE: OFF
      WITH_BUILDINFO: OFF
      WITH_GAMEENGINE: OFF
