---

- name: Install dependancies
  apt:
    name:
      - meson
      - dh-autoreconf
      - libxcb-keysyms1-dev
      - libpango1.0-dev
      - libxcb-util0-dev
      - xcb
      - libxcb1-dev
      - libxcb-icccm4-dev
      - libyajl-dev
      - libev-dev
      - libxcb-xkb-dev
      - libxcb-cursor-dev
      - libxkbcommon-dev
      - libxcb-xinerama0-dev
      - libxkbcommon-x11-dev
      - libstartup-notification0-dev
      - libxcb-randr0-dev
      - libxcb-xrm0
      - libxcb-xrm-dev
      - libxcb-shape0
      - libxcb-shape0-dev
  become: true

- name: Clone repo
  git:
    clone: true
    dest: "{{ home_dir }}/Downloads/i3-gaps"
    force: true
    repo: https://github.com/Airblader/i3
    update: true

- name: Create build folder
  file:
    state: directory
    path: "{{ home_dir }}/Downloads/i3-gaps/build"
    mode: '0755'

- name: i3-gaps meson
  command: "meson {{ home_dir }}/Downloads/i3-gaps"
  args:
    chdir: "{{ home_dir }}/Downloads/i3-gaps/build"

- name: i3-gaps ninja
  command: ninja
  args:
    chdir: "{{ home_dir }}/Downloads/i3-gaps/build"

- name: i3-gaps ninja install
  command: ninja install
  args:
    chdir: "{{ home_dir }}/Downloads/i3-gaps/build"
  become: true
