---
#TODO: Build from source
- name: Remove snap Firefox
  community.general.snap:
    name: firefox
    state: absent
  become: true

- name: Install firefox
  apt: 
    name: firefox
  become: true

- name: Create distribution folder
  file:
    path: '/etc/firefox/policies'
    state: directory
    mode: 0755
  become: true

- name: Distribute firefox policy
  copy:
    src: templates/firefox/policies.json
    dest: "/etc/firefox/policies/policies.json"
  become: true

# TESTS
# Check /snap/firefox doesn't exist
# Launch firefox
# Verify policies are applied
