---
#TODO: replace with apt install (but only on pop-os)

- name: Install firefox
  apt:
    name: firefox
  become: true

- name: Create distribution folder
  file:
    path: '/etc/firefox/policies'
    state: directory
    mode: 0755
  become: true

- name: Distribute firefox policy
  file:
    src: "{{ home_dir }}/Workspace/dotfiles-playbook/templates/firefox/policies.json"
    dest: "/etc/firefox/policies/policies.json"
    state: link
  become: true

# TESTS
# Launch firefox
# Verify policies are applied
