---
#TODO: Build from source
- name: Remove snap Firefox
  community.general.snap:
    name: firefox
    state: absent
  become: yes

- name: Install firefox
  apt: 
    name: firefox
  become: yes

- name: Create firefox distribution directory
  file:
    path: "/etc/firefox/distribution/"
    state: directory
  become: true

- name: Distribute firefox policy
  copy:
    src: templates/firefox/policies.json
    dest: "/etc/firefox/distribution/policies.json"
  become: true
