---

- name: apt autoremove
  apt:
    autoremove: yes

- name: Locate all files in /tmp
  find:
    path: /tmp
  register: cleanup
  ignore_errors: true

- name: Empty /tmp
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ cleanup.files }}"
  ignore_errors: true

- name: User manual entry:
  debug:
    msg: "{{ item }}"
  loop:
    - "Create Git SSH key for Github connection"
    - "Double check that Alacritty uses zsh and GNOME terminal defaults to bash"
    - "It's recommended that the machine get rebooted after running this Playbook"
