---

- name: apt clean and remove
  apt:
    autoclean: true
    autoremove: true
  become: true

- name: Remove files from $HOME
  file:
    path: "{{ home_dir }}/{{item}}"
    state: absent
  with_items:
    - .shell.pre-oh-my-zsh
    - .sudo_as_admin_successful
    - .viminfo
    - .zshrc.pre-oh-my-zsh

- name: Clean up downloads
  file:
    path: "{{ home_dir }}/Downloads"
    state: "{{ item }}"
  with_items:
    - absent
    - directory
