---

#TODO: move firefox policies
- name: Distribute firefox policy
  copy:
    src: templates/firefox/policies.json
    dest: /usr/lib/firefox/distribution/policies.json

- name: apt autoremove
  apt:
    autoremove: yes

- name: Clean up downloads 
  file:
    path: "{{ home_dir }}/Downloads" 
    state: "{{ item }}" 
  with_items:
    - absent
    - directory

- name: User manual entry
  debug:
    msg: "{{ item }}"
  loop:
    - "Create Git SSH key for Github connection"
    - "Configure fingerprint reader"
    - ":PaqInstall in nvim"
    - "It's recommended that the machine get rebooted after running this Playbook"
