---

- name: install
  apt:
    name: git

- name: Move git config
  copy:
    src: templates/git-config/gitconfig
    dest: "{{ home_dir }}/.gitconfig"

# TODO: gh-cli?
# TODO: core.editor = nvim

# Tests
# cat $HOME/.gitconfig
