---

- name: install
  apt:
    name: git
    only_upgrade: true
  become: true

- name: Move git config
  file:
    src: "{{ home_dir }}/workspace/dotfiles-playbook/templates/git-config/gitconfig"
    dest: "{{ home_dir }}/.gitconfig"
    state: link
  when: not ansible_check_mode

# Tests
# cat $HOME/.gitconfig
