---

- name: install
  apt:
    name: git
    only_upgrade: true
  become: true

- name: Move git config
  file:
    src: "{{ home_dir }}/Workspace/dotfiles-playbook/templates/git-config/gitconfig" 
    dest: "{{ home_dir }}/.gitconfig"
    state: link

# Tests
# cat $HOME/.gitconfig
