---

- name: install
  apt:
    name: git

- name: Set git username
  command: "git config --global user.name {{ git_user }}"

- name: Set git email
  command: "git config --global user.name {{ git_email }}"

# TODO: gh-cli?
# TODO: core.editor = nvim

# Tests
# cat $HOME/.gitconfig
