---

- name: Remove prior Go Install
  file:
    path: "/usr/local/go"
    state: absent
  become: True

- name: Download Go
  get_url:
    url: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
    dest: "{{ home_dir }}/Downloads/go.tar.gz"

- name: Install Go
  unarchive:
    src: "{{ home_dir }}/Downloads/go.tar.gz"
    dest: "/usr/local/"
  become: True

#TODO: Fix gopls
# - name: Gopls - Install
#   shell: /usr/local/go/bin/go install golang.org/x/tools/gopls@latest

# Tests
# Run `go version`
