---

- name: Install i3
  apt:
    name: i3

#TODO: Transfer i3 config
#TODO: Set up polybar and install 

# Install polybar (not available on ubuntu Trusty)
#- name: polybar
#  apt:
#    name: polybar

- name: Install light
  apt:
    name: light

- name: Give light permissions to control screen brightness
  command: chmod +s /usr/bin/light

- name: rofi searchbar
  apt:
    name: rofi

#TODO: Transfer rofi config and theme file

