---
#TODO: Find better wallpaper?

- name: Download wallpaper directory
  git:
    clone: true
    repo: https://gitlab.com/dwt1/wallpapers.git
    dest: "{{ home_dir }}/.wallpapers"

# Apparently it's better to overwrite standard i3 to avoid errors
- name: Install i3
  apt:
    name: i3
  become: true

- name: Build i3-gaps
  include_tasks: build_i3.yml

- name: Distribute i3 config
  copy:
    src: "templates/i3-config/{{ item }}"
    dest: "{{ home_dir }}/.config/i3/"
  with_items:
    - config
    - i3lock.sh


# For managing wallpapers in i3/config
- name: Install feh
  apt:
    name: feh
  become: true

- name: Intall Rofi searchbar
  apt:
    name: rofi
  become: true

- name: Distribute Rofi config
  copy:
    src: templates/i3-config/rofi-config/
    dest: "{{ home_dir }}/.config/rofi"

- name: Install polybar
  apt:
    name: polybar
  become: true

- name: Distribute polybar config
  copy:
    src: templates/i3-config/polybar/
    dest: "{{ home_dir }}/.config/polybar"
    mode: +x

- name: Install picom
  apt:
    name: picom
  become: true

- name: Distribute picom config
  copy:
    src: templates/i3-config/picom/
    dest: "{{ home_dir }}/.config/picom"
    mode: +x

# For brightness control
- name: Install light
  apt:
    name: light
  become: true

- name: Give light perms to manage screen brightness
  file:
    path: /usr/bin/light
    mode: +s
  become: true

# https://cravencode.com/post/essentials/enable-tap-to-click-in-i3wm/
- name: Enable tap-to-click for touchpad
  copy:
    src: templates/internal-configs/90-touchpad.conf
    dest: /etc/X11/xorg.conf.d/
  become: true

# TESTS
# relog into i3-gaps
# Does the wallpaper appear?
# Can you launch the rofi searchbar
# Does Polybar appear as expected
