---
#TODO: Find better wallpaper?

- name: Download wallpaper
  get_url:
    url: "{{ wallpaper_url }}"
    dest: "{{ home_dir }}/Workspace/wallpaper.jpg"

# Apparently it's better to overwrite standard i3 to avoid errors
- name: Install i3
  apt:
    name: i3
  become: true

# TODO: Enable when gaps is supported
- name: Add regolith linux PPA
  apt_repository:
    repo: "ppa:regolith-linux/release"
  become: true
  when: ansible_facts['distribution_version'] == '21.10'

- name: Install i3-gaps
  apt:
    name: i3-gaps
  become: true
  when: ansible_facts['distribution_version'] == '21.10'

- name: Distribute i3 config
  copy:
    src: templates/i3-config/config
    dest: "{{ home_dir }}/.config/i3/"

# For managing wallpapers in i3/config
- name: Install feh
  apt:
    name: feh
  become: true

- name: Intall Rofi searchbar
  apt:
    name: rofi
  become: true

- name: Distribute Rofi config
  copy:
    src: templates/i3-config/rofi-config/
    dest: "{{ home_dir }}/.config/rofi"

- name: Install polybar
  apt:
    name: polybar
  become: true

- name: Distribute polybar config
  copy:
    src: templates/i3-config/polybar/
    dest: "{{ home_dir }}/.config/polybar"
    mode: +x

- name: Install picom
  apt:
    name: picom
  become: true

- name: Distribute picom config
  copy:
    src: templates/i3-config/picom/
    dest: "{{ home_dir }}/.config/picom"

# For brightness control
- name: Install light
  apt:
    name: light
  become: true

- name: Give light perms to manage screen brightness
  file:
    path: /usr/bin/light
    mode: +s
  become: true

# TESTS
# relog into i3-gaps
# Does the wallpaper appear?
# Can you launch the rofi searchbar
# Does Polybar appear as expected
