---

- name: Update
  apt:
    update_cache: true
    upgrade: dist
    force_apt_get: true

- name: Remove unneeded folders
  file:
    state: absent
    path: "{{ home_dir }}/{{ item }}"
  with_items:
    - "Documents"
    - "Music"
    - "Pictures"
    - "Public"
    - "Templates"
    - "Videos"

- name: Create Workspace folder
  file:
    state: directory
    path: "{{ home_dir }}/Workspace"
    mode: '0755'

- name: Check for font presence
  stat:
    path: "{{ home_dir }}/.local/share/fonts/Droid Sans Mono Nerd Font Complete.otf"
  register: p 
  
- name: Download DroidSansMono font
  get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete%20Mono.otf" 
    dest: "{{ home_dir }}/.local/share/fonts"
  when: not p.stat.exists

- name: reload fonts
  command: fc-cache -f -v
  when: not p.stat.exists

  # Only relevant for framework laptop
- name: Download Framework fingerprint reader script
  get_url:
    url: bit.ly/FP_Reader
    dest: /tmp/FP_Reader.sh

- name: Install Framework fingerprint reader
  command: sh /tmp/FP_Reader.sh
