---

- name: Update
  apt:
    update_cache: true
    upgrade: dist
    force_apt_get: true

- name: Remove unneeded folders
  file:
    state: absent
    path: "{{ home_dir }}/{{ item }}"
  with_items:
    - "Documents"
    - "Music"
    - "Pictures"
    - "Public"
    - "Templates"
    - "Videos"

- name: Create Workspace folder
  file:
    state: directory
    path: "{{ home_dir }}/Workspace"
    mode: '0755'

- name: Check for Iosevka presence
  stat:
    path: "/tmp/Iosevka"
  register: p 
  
- name: Download Iosevka font
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Iosevka.zip
    dest: "/tmp/Iosevka"
  when: not p.stat.exists

- name: Install Iosevka font
  unarchive:
    src: "/tmp/Iosevka"
    dest: /usr/share/fonts
  when: not p.stat.exists

- name: reload fonts
  command: fc-cache -f -v
  when: not p.stat.exists

  # Only relevant for framework laptop
- name: Download Framework fingerprint reader script
  get_url:
    url: bit.ly/FP_Reader
    dest: /tmp/FP_Reader.sh

- name: Install Framework fingerprint reader
  command: sh /tmp/FP_Reader.sh
