---

- name: Remove unneeded folders
  file:
    state: absent
    path: "{{ home_dir }}/{{ item }}"
  with_items:
    - "Desktop"
    - "Documents"
    - "Music"
    - "Pictures"
    - "Public"
    - "Templates"
    - "Videos"

- name: Create required directories
  file:
    state: directory
    path: "{{ home_dir }}/{{ item }}"
    mode: '0755'
  with_items:
    - "Workspace"
    - "Applications"
    - ".config/alacritty"
    - ".config/i3"
    - ".config/tmux"
    - ".local/share/fonts"

- name: Install Font
  block:
    - name: Download
      get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/DroidSansMono.tar.xz
        dest: "{{ home_dir }}/Downloads//DroidSansMono.tar.xz"

    - name: Install
      unarchive:
        src: "{{ home_dir }}/Downloads//DroidSansMono.tar.xz"
        dest: "{{ home_dir }}/.local/share/fonts/"
      become: true

- name: reload fonts
  command: fc-cache -f -v

- name: Clone dotfiles repo to correct location
  git:
    repo: https://github.com/Ttibsi/dotfiles-playbook
    dest: "{{ home_dir }}/Workspace/dotfiles-playbook"
  when: not ansible_check_mode

# Tests:
# Check folders exist manually using ls
# `fc-list | grep "Droid"
