---
- name: Update
  apt:
    update_cache: true
    upgrade: dist
    force_apt_get: true

- name: Remove unneeded folders
  file:
    state: absent
    path: "{{ home_dir }}/{{ item }}"
  with_items:
    - "Documents"
    - "Music"
    - "Pictures"
    - "Public"
    - "Templates"
    - "Videos"

- name: Create Workspace and fonts folders
  file:
    state: directory
    path: "{{ home_dir }}/{{ item }}"
    mode: '0755'
  with_items:
    - "Workspace"
    - ".local/share/fonts"

# Potentially change
#- name: Download DroidSansMono font
#  get_url:
#    url: "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete.otf"
#    dest: "{{ home_dir }}/.local/share/fonts/Droid Sans Mono Nerd Font Complete.otf"

- name: Install SFmono
  git:
    repo: https://github.com/shaunsingh/SFMono-Nerd-Font-Ligaturized.git
    dest: "{{ home_dir }}/.local/share/fonts/"

- name: reload fonts
  command: fc-cache -f -v

# Tests:
# Check folders exist manually using ls
# `fc-list | grep "Droid"
