---

- name: Update
  apt:
    update_cache: true
    upgrade: dist
    force_apt_get: true

- name: Remove unneeded folders
  file:
    state: absent
    path: "{{ home_dir }}/{{ item }}"
  with_items:
    - "Documents"
    - "Music"
    - "Pictures"
    - "Public"
    - "Templates"
    - "Videos"

- name: Create Workspace folder
  file:
    state: directory
    path: "{{ home_dir }}/Workspace"
    mode: '0755'

- name: Download DroidSansMono font
  get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete.otf"
    dest: "{{ home_dir }}/.local/share/fonts/Droid Sans Mono Nerd Font Complete.otf"

- name: reload fonts
  command: fc-cache -f -v

  # Only relevant for framework laptop
- name: Download Framework fingerprint reader script
  get_url:
    url: "http://elevatedsystems.tech/media/scripts/FP_Reader_install.sh"
    dest: "{{ home_dir }}/Downloads/FP_Reader.sh"

#- name: Install Framework fingerprint reader
#  command: sh "{{ home_dir }}/Downloads/FP_Reader.sh"
