---
- name: Update
  apt:
    update_cache: true
    upgrade: dist
    force_apt_get: true
  become: true

- name: Remove unneeded folders
  file:
    state: absent
    path: "{{ home_dir }}/{{ item }}"
  with_items:
    - "Documents"
    - "Music"
    - "Pictures"
    - "Public"
    - "Templates"
    - "Videos"

- name: Create required directories
  file:
    state: directory
    path: "{{ home_dir }}/{{ item }}"
    mode: '0755'
  with_items:
    - "Workspace"
    - "Applications"
    - ".config/i3"
    - ".local/share/fonts"

- name: Install SFmono
  git:
    repo: https://github.com/shaunsingh/SFMono-Nerd-Font-Ligaturized.git
    dest: "{{ home_dir }}/.local/share/fonts/"

- name: reload fonts
  command: fc-cache -f -v

# Tests:
# Check folders exist manually using ls
# `fc-list | grep "Droid"
