---

- name: ansible env
  debug
    msg: "{{ ansible_env.HOME }}"

- name: Update
  apt:
    update_cache: true
    upgrade: dist
    force_apt_get: true

- name: Remove unneeded folders
  file:
    state: absent
    path: "{{ ansible_env.HOME }}/{{ item }}"
  with_items:
    - "Documents"
    - "Music"
    - "Pictures"
    - "Public"
    - "Templates"
    - "Videos"

- name: Create Workspace folder
  file:
    state: directory
    path: "{{ ansible_env.HOME }}/Workspace"
    mode: '0755'
  
- name: Download Iosevka font
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Iosevka.zip
    dest: "/tmp/Iosevka"

- name: Install Iosevka font
  unarchive:
    src: "/tmp/Iosevka"
    dest: /usr/share/fonts

- name: reload fonts
  command: fc-cache -f -v
