---

- name: Update
  apt:
    update_cache: true
    upgrade: dist
    force_apt_get: true

- name: Remove unneeded folders
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "$HOME/Documents"
    - "$HOME/Music"
    - "$HOME/Pictures"
    - "$HOME/Public"
    - "$HOME/Templates"
    - "$HOME/Videos"

- name: Create Workspace folder
  file:
    path: "$HOME/Workspace"
    state: directory
    mode: '0755'
  
- name: Download Iosevka font
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Iosevka.zip
    dest: "/tmp/Iosevka"

- name: Install Iosevka font
  unarchive:
    src: "/tmp/Iosevka"
    dest: /usr/share/fonts

- name: reload fonts
  command: fc-cache -f -v
