---

- name: Update
  apt:
    update_cache: true
    upgrade: dist
    force_apt_get: true

- name: Remove unneeded folders
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - Documents
    - Music
    - Pictures
    - Public
    - Templates
    - Videos

- name: Create Workspace folder
  file:
    path: Workspace
    state: directory
    mode: '0755'
  
