---

- name: Remove unneeded folders
  file:
    state: absent
    path: "{{ home_dir }}/{{ item }}"
  with_items:
    - "Desktop"
    - "Documents"
    - "Music"
    - "Pictures"
    - "Public"
    - "Templates"
    - "Videos"

- name: Create required directories
  file:
    state: directory
    path: "{{ home_dir }}/{{ item }}"
    mode: '0755'
  with_items:
    - "Workspace"
    - "Applications"
    - ".config/i3"
    - ".config/alacritty"
    - ".local/share/fonts"

- name: Install Font
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete%20Mono.otf
    dest: "{{ home_dir }}/.local/share/fonts/"

- name: reload fonts
  command: fc-cache -f -v

- name: Clone this repo to correct location
  git:
    repo: https://github.com/Ttibsi/dotfiles-playbook
    dest: "{{ home_dir }}/Workspace/dotfiles-playbook"
    version: master

# Tests:
# Check folders exist manually using ls
# `fc-list | grep "Droid"
