---

- name: PythonLSP - pyright
  pip:
    name: python-language-server
    virtualenv: "{{ home_dir }}/.opt/venv"

- name: Install cmake-language-server
  pip:
    name: cmake-language-server
    virtualenv: "{{ home_dir }}/.opt/venv"

- name: luaLSP
  block:
    - name: luaLSP - Create dir
      file:
        path: "{{ home_dir}}/.opt/lua-language-server/"
        state: directory
        mode: 0755

    - name: luaLSP - Download
      get_url:
        url: "https://github.com/LuaLS/lua-language-server/releases/download/{{lua_lsp_version}}/lua-language-server-{{lua_lsp_version}}-linux-x64.tar.gz"
        dest: "{{ home_dir }}/Downloads/lua-language-server.tar.gz"

    - name: luaLSP - Install
      unarchive:
        src: "{{ home_dir }}/Downloads/lua-language-server.tar.gz"
        dest: "{{ home_dir }}/.opt/lua-language-server"
        mode: 0755
      become: true
      when: not ansible_check_mode

- name: Gopls - Install
  shell: /usr/local/go/bin/go install golang.org/x/tools/gopls@latest

# This directory only exists after gopls is installed, can't be in tasks/go.yml
- name: Move Go directory
  copy:
    src: "{{ home_dir }}/go"
    dest: "{{ home_dir }}/.go"
    remote_src: yes
  when: not ansible_check_mode
