---

- name: PythonLSP - pyright
  community.general.npm:
    name: pyright
    global: yes
  become: true

- name: luaLSP - Sumneko - Download
  get_url:
    url: "https://github.com/sumneko/lua-language-server/releases/download/{{lua_lsp_version}}/lua-language-server-{{lua_lsp_version}}-linux-x64.tar.gz"
    dest: "{{ home_dir }}/Downloads/lua-language-server.tar.gz"

- name: luaLSP - Sumneko - Install
  unarchive:
    src: "{{ home_dir }}/Downloads/lua-language-server.tar.gz"
    dest: "{{ home_dir }}/.local/bin/lua-language-server"
    mode: 0755
    creates: yes
  become: true
