---

- name: Blueman
  apt:
    name: blueman
  become: true

- name: Bottom
  apt:
    deb: https://github.com/ClementTsang/bottom/releases/download/0.6.8/bottom_0.6.8_amd64.deb
  become: true

- name: Cowsay
  apt:
    name: cowsay
  become: true

- name: Curl
  apt:
    name: curl
  become: true

- name: Neofetch
  apt:
    name: neofetch
  become: true

- name: Pipes
  block:
    - name: Clone Pipes repo
      git:
        clone: true
        dest: "{{ home_dir }}/Downloads/pipes"
        force: true
        repo: https://github.com/pipeseroni/pipes.sh.git
        update: true

    - name: Install pipes
      make:
        target: install
        chdir: "{{ home_dir }}/Downloads/pipes"
      become: true

- name: Powertop
  apt:
    name: powertop
  become: true

- name: TLP
  apt:
    name: tlp
  become: true

- name: Tmux
  block:
    - name: Install Tmux
      apt:
        name: tmux
      become: true

    - name: Copy tmux config
      file:
        src: "{{ home_dir }}/Workspace/dotfiles-playbook/templates/tmux/tmux.conf"
        dest: "{{ home_dir }}/.config/tmux/tmux.conf"
        state: link

- name: Tree
  apt:
    name: tree
  become: true

- name: unzip
  apt:
    name: unzip
  become: true

- name: Video codecs
  command: sudo DEBIAN_FRONTEND=noninteractive apt install -y ubuntu-restricted-extras

- name: Xclip
  apt:
    name: xclip
  become: true

# Tests
# Run neofetch, cowsay, btm
