---

- name: Bottom 
  apt:
    deb: https://github.com/ClementTsang/bottom/releases/download/0.6.8/bottom_0.6.8_amd64.deb
  become: yes

- name: Cowsay
  apt:
    name: cowsay
  become: yes

- name: Curl
  apt:
    name: curl
  become: yes

- name: Neofetch
  apt:
    name: neofetch
  become: yes

- name: Tree
  apt:
    name: tree
  become: yes

- name: unzip
  apt:
    name: unzip
  become: yes

- name: Video codecs
  command: sudo DEBIAN_FRONTEND=noninteractive apt install -y ubuntu-restricted-extras

# Tests
# Run neofetch, cowsay, btm
