---

- name: Install dependencies
  apt:
    name:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
      - doxygen
    state: latest

- name: Clone repo
  git:
    clone: yes
    dest: "/tmp/nvim"
    force: yes
    repo: https://github.com/neovim/neovim.git
    single_branch: yes
    update: yes
  register: clone

- name: Build nvim
  make:
    chdir: "/tmp/nvim"
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo

- name: Install nvim
  make:
    chdir: "/tmp/nvim"
    target: install

# move templates/nvim to .config/nvim
