---

- name: Install dependencies
  apt:
    name:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
      - doxygen
    state: latest

- name: Clone repo
  git:
    clone: yes
    dest: "{{ home_dir }}/Downloads/nvim"
    force: yes
    repo: https://github.com/neovim/neovim.git
    single_branch: yes
    update: yes
    version: "{{ nvim_version }}"
  register: clone

- name: Build nvim
  make:
    chdir: "{{home_dir }}/Downloads/nvim"
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo
  when: clone.changed

# This installs to /usr/local/bin/
- name: Install nvim
  make:
    chdir: "{{ home_dir }}/Downloads/nvim"
    target: install
  when: clone.changed

#TODO: figure out why nvim plugins aren't working

- name: Install paq lua plugin manager
  git:
    repo: https://github.com/savq/paq-nvim.git
    dest: "{{ home_dir}}/.local/share/nvim/site/pack/paqs/start/paq-nvim"
    version: master

- name: Install gcc compiler for treesitter
  apt:
    name: 
      - gcc
      - build-essential

- name: Distribute nvim config
  copy:
    src: templates/nvim/
    dest:  "{{ home_dir }}/.config/nvim/"
