---

- name: Install dependencies
  apt:
    name:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
      - doxygen
      # For clipboard manupulation
      - xclip
    state: latest
  become: true

- name: Clone repo
  git:
    clone: true
    dest: "{{ home_dir }}/Downloads/nvim"
    force: true
    repo: https://github.com/neovim/neovim.git
    update: true
    version: "{{ nvim_version }}"
  register: clone

- name: Build nvim
  make:
    chdir: "{{ home_dir }}/Downloads/nvim"
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo
  when: clone.changed

# This installs to /usr/local/bin/
- name: Install nvim
  make:
    chdir: "{{ home_dir }}/Downloads/nvim"
    target: install
  when: clone.changed
  become: true

- name: Install paq package manager
  git:
    clone: true
    repo: https://github.com/savq/paq-nvim.git
    dest: "{{ home_dir }}/.local/share/nvim/site/pack/paqs/start/paq-nvim/"
    force: true
    update: true

- name: Install plugin dependencies
  apt:
    name:
      # gcc for Treesitter
      - gcc
      - build-essential
  become: true
  when: not ansible_check_mode

- name: Install language servers
  include_tasks: lang_serv.yml

- name: Distribute nvim config
  file:
    src: "{{ home_dir }}/Workspace/dotfiles-playbook/templates/nvim"
    dest: "{{ home_dir }}/.config/nvim"
    state: link
    force: True

- name: Install nvim plugins
  command: nvim --headless -c 'PaqInstall' +q

# Tests
# Open nvim and verify version
# Verify paq install by running :PaqList
# Check if treesitter is installing when you first open nvim
# Verify files have been copied to `~/.config/nvim`
# Run :LspInfo to check if all LSPs are working and open files of each type
