---

- name: Install dependencies
  apt:
    name:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
      - doxygen
    state: latest

- name: Clone repo
  git:
    clone: yes
    dest: "{{ home_dir }}/Downloads/nvim"
    force: yes
    repo: https://github.com/neovim/neovim.git
    update: yes
    version: "{{ nvim_version }}"
  register: clone

- name: Build nvim
  make:
    chdir: "{{home_dir }}/Downloads/nvim"
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo
  when: clone.changed

# This installs to /usr/local/bin/
- name: Install nvim
  make:
    chdir: "{{ home_dir }}/Downloads/nvim"
    target: install
  when: clone.changed
