---

- name: Install dependencies
  ansible.builtin.package:
    name:
      - base-devel
      - cmake
      - curl
      - ninja
      - tree-sitter
      - unzip
    state: latest

- name: Clone repo
  git:
    clone: yes
    dest: "{{ ansible_env.HOME }}/tmp/nvim"
    force: yes
    repo: https://github.com/neovim/neovim.git
    single_branch: yes
    update: yes
  register: clone

- name: Build nvim
  make:
    chdir: "{{ ansible_env.HOME }}/tmp/nvim"
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo

- name: Install nvim
  make:
    chdir: "{{ ansible_env.HOME }}/tmp/nvim"
    target: install


