---

- name: Add deadsnakes ppa
  apt_repository:
    repo: ppa:deadsnakes/ppa

- name: Install pip 
  apt:
    name: python3-pip

- name: Install py3.10
  apt:
    name: python3.10

- name: Install py3.10-distutils
  apt:
    name: python3.10-distutils 

- name: Download get-pip script
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py 
    dest: "/tmp/get-pip.py"
    mode: 0755

- name: Install pip3.10
  command: python3.10 "/tmp/get-pip.py"

- name: Install pre-commit
  pip:
    name: pre-commit

- name: Download ghstat
  git:
    repo: https://github.com/Ttibsi/gh-stats
    dest: "/tmp/gh-stats"
  environment:
    GIT_TERMINAL_PROMPT: 0 

#TODO: test and get working ghstat
- name: Install ghstat
  command: "python3.10 -m pip install /tmp/gh-stats" 
