---

- name: Add deadsnakes ppa
  apt_repository:
    repo: ppa:deadsnakes/ppa
  become: yes

# https://youtu.be/O390_abzo08
- name: curl virtualenv
  get_url:
    url: https://bootstrap.pypa.io/virtualenv.pyz
    dest: "{{ home_dir }}/Downloads/virtualenv.pyz"

- name: Install virtualenv script 
  script:
    cmd: "{{ home_dir }}/Downloads/virtualenv.pyz {{ home_dir }}/opt/venv"
    executable: python3

- name: Create venv
  script:
    cmd: "{{ home_dir }}/opt/venv/bin/pip install virtualenv"
    executable: python3

- name: Create symlink
  file:
    src: "{{ home_dir }}/opt/venv/bin/virtualenv" 
    dest: "/bin/virtualenv"
    state: link

- name: Install gh-stats
  pip:
    name: git+https://github.com/ttibsi/gh-stats
    virtualenv: "{{ home_dir }}/opt/venv"

- name: Symlink gh-stats
  file:
    src: "{{ home_dir }}/opt/venv/bin/ghstats"
    dest: "/bin/ghstats"
    state: link

# Tests
# python3.10 --version
# pre-commit --version
