---

- name: Add deadsnakes ppa
  apt_repository:
    repo: ppa:deadsnakes/ppa
  become: true
  when: ansible_facts['distribution_release'] == 'jammy'

# Anthony Explains 79
# TLDR I'm not installing a global/system version of pip
# Each project has it's own venv
# Global installs are symlinks
- name: curl virtualenv
  get_url:
    url: https://bootstrap.pypa.io/virtualenv.pyz
    dest: "{{ home_dir }}/Downloads/virtualenv.pyz"

- name: Install virtualenv script
  script:
    cmd: "{{ home_dir }}/Downloads/virtualenv.pyz {{ home_dir }}/.opt/venv"
    executable: python3
  when: not ansible_check_mode

- name: Create venv
  script:
    cmd: "{{ home_dir }}/.opt/venv/bin/pip install virtualenv"
  when: not ansible_check_mode

- name: Create symlink
  file:
    src: "{{ home_dir }}/.opt/venv/bin/virtualenv"
    dest: "/bin/virtualenv"
    state: link
  become: true
  when: not ansible_check_mode

- name: Install pre-commit
  pip:
    name: pre-commit
    virtualenv: "{{ home_dir }}/.opt/venv"

- name: Symlink pre-commit
  file:
    src: "{{ home_dir }}/.opt/venv/bin/pre-commit"
    dest: "{{ home_dir }}/.opt/pre-commit"
    state: link
  become: true

- name: Install gh-stats
  pip:
    name: git+https://github.com/ttibsi/gh-stats
    virtualenv: "{{ home_dir }}/.opt/venv"

- name: Symlink gh-stats
  file:
    src: "{{ home_dir }}/.opt/venv/bin/ghstats"
    dest: "{{ home_dir  }}/.opt/ghstats"
    state: link
  become: true

# Tests
# ghstats --help
# virtualenv --version
