---

- name: Install zsh
  apt:
    name: zsh
  become: true

- name: Check for omz
  stat:
    path: "{{ home_dir }}/.oh-my-zsh"
  register: zsh_exist
  
- name: Download ohmyzsh
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: "{{ home_dir }}/Downloads/zsh-install.sh"
    mode: '0755'
  when: not zsh_exist.stat.exists

- name: Execute zsh-install.sh
  shell: sh "{{ home_dir }}/Downloads/zsh-install.sh"
  become: false
  when: not zsh_exist.stat.exists

# This needs to be after omz install or it'll overwrite it - `.zshrc-pre-oh-my-zsh`
- name: Distribute zshrc
  copy:
    src: "templates/zsh-shell/zshrc"
    dest: "{{ home_dir }}/.zshrc"

- name: Distribute OMZ
  copy:
    src: templates/zsh-shell/.oh-my-zsh/
    dest: "{{ home_dir }}/.oh-my-zsh/"
  when: not zsh_exist.stat.exists

- name: Download p10k
  git:
    clone: yes
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ home_dir }}/.oh-my-zsh/custom/themes/powerlevel10k/"
    force: yes

- name: Distribute p10k config
  copy:
    src: templates/zsh-shell/p10k.zsh
    dest: "{{ home_dir }}/.p10k.zsh"

- name: Clone zsh-autosuggestions
  ansible.builtin.git:
    clone: yes
    depth: 1
    dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    repo: https://github.com/zsh-users/zsh-autosuggestions
    update: yes
    version: master

- name: Clone zsh-completions
  ansible.builtin.git:
    clone: yes
    depth: 1
    dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-completions"
    repo: https://github.com/zsh-users/zsh-completions
    update: yes
    version: master

- name: Clone zsh-syntax-highlighting
  ansible.builtin.git:
    clone: yes
    depth: 1
    dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    update: yes
    version: master

# Tests
# Can you enter zsh (`zsh`)
# Does OMZ and p10k launch properly
# Does p10k appear properly (Has the font installed properly)
# Enter text to test if the zsh plugins are working
