---

- name: Install zsh
  apt:
    name: zsh

- name: Download ohmyzsh
  get_url:
    dest: "/tmp/zsh-install.sh"
    mode: '0755'
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh

- name: Execute zsh-install.sh
  shell: "./tmp/zsh-install.sh"

# Distribute zsh template here
- name: Distribute zshrc 
  copy:
    src: "templates/zsh-shell/.zshrc" 
    dest: "{{ home_dir }}"

- name: Distribute OMZ
  copy:
    src: /templates/zsh-shell/.oh-my-zsh/
    dest: "{{ home_dir }}/.oh-my-zsh/custom"

- name: Download p10k
  git:
    clone: yes
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ home_dir }}/.oh-my-zsh/themes/powerlevel10k"
    single_branch: yes
    force: yes
  register: clone

- name: Distribute p10k config
  copy:
    src: /templates/zsh-shell/.p10k.zsh
    dest: "{{ home_dir }}"

   
- name: Clone zsh-autosuggestions
  ansible.builtin.git:
    clone: yes
    depth: 1
    dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    repo: https://github.com/zsh-users/zsh-autosuggestions
    single_branch: yes
    update: yes
    version: master

- name: Clone zsh-completions
  ansible.builtin.git:
    clone: yes
    depth: 1
    dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-completions"
    repo: https://github.com/zsh-users/zsh-completions
    single_branch: yes
    update: yes
    version: master

- name: Clone zsh-syntax-highlighting
  ansible.builtin.git:
    clone: yes
    depth: 1
    dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    single_branch: yes
    update: yes
    version: master
